services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb://mongo:27017/synapse
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_EXCHANGE_NAME=synapse.events
      - RABBITMQ_EXCHANGE_TYPE=topic
      - RABBITMQ_QUEUE=notifications
    env_file:
      - .env
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=mongodb://mongo:27017/synapse
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - RABBITMQ_EXCHANGE_NAME=synapse.events
      - RABBITMQ_EXCHANGE_TYPE=topic
      - RABBITMQ_QUEUE=notifications
    depends_on:
      - mongo
      - rabbitmq

volumes:
  mongodb_data:
